<h1 class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Privacy Policy</span></span></h1>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We, at DoodlePad.In, take your privacy very seriously and abide by the following policy to ensure your satisfaction. If you have any concerns, please do not hesitate to contact us</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">WHAT INFORMATION DOES DOODLEPAD.IN COLLECT/TRACK ABOUT ME</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">DoodlePad.In's sole purpose is to assist you in finding your companion securely and privately. Whether you are seeking friendship, social networking, dating or a serious relationship, DoodlePad.In is here to help you.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To accomplish the above purpose, our members create unique profiles (provide personal information) and our matching technology provides matches based on pre-selected criteria.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">The public (visitors, users, excluding employees of DoodlePad.In or DoodlePad.In&rsquo;s service providers or the financial institutions used to process membership charges) cannot use the information we gather to identify specific individuals.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Further, in order to facilitate commerce, might collect credit card or debit card information, member's address, or bank information only from those who choose to join DoodlePad.In. Visitors to our site may browse, search and view user profiles or features without entering any personal information.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">WHERE THIS PRIVACY POLICY APPLIES</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">The Policy applies to websites/apps, blogs or any services operated by DoodlePad.In. For this, we refer to all of these as our &ldquo;services&rdquo; in this Privacy Policy. To make it extra clear, we&rsquo;ve added links to this Privacy Policy on all applicable services.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Some services may have their own privacy policy. If any service has its own policy, then that policy &ndash; not this Privacy Policy &ndash; applies.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">INFORMATION WE COLLECT</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We need some details to develop meaningful relations with information about you, such as basic profile details and the types of people you&rsquo;d like to meet. We also collect information generated as you use our services, for example access logs, as well as information from third parties, like when you access our services through a social media account. If you want additional info, we go into more detail below.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Information you give us</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">This is the information you choose to give us when using our services. This includes:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">When you create account, you provide us with at least login credentials, as well as some basic details necessary for the service to work, such as your gender and date of birth.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">When you create your profile, you share additional information, such as details on your personality, interests and other details, as well as content such as photos and videos. To add certain content, like pictures or videos, you may allow us to access your camera or photo album. Some of the information you choose to provide us may be considered &ldquo;special&rdquo; or &ldquo;sensitive&rdquo; in certain jurisdictions, for example your racial or ethnic origins, sexual orientation and religious beliefs. By choosing to provide this information, you consent to our processing of that information.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">When you subscribe our services or make a purchase from us (rather than via a platform such as iOS or Android), you provide us or the payment service provider with information, such as your debit or credit card number or other financial information.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">When you take part in surveys, you give us insights on products and services, responses to questions and testimonials.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">When you participate in promotions, contests, we gather details that you use to register or enter.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">When contacting customer care team, we gather details you give us during the process. Sometimes, we monitor or record these interactions for training purposes and to ensure a high quality of service.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">If you ask us to communicate with or otherwise process information of other people (for example, if you ask us to send an email on your behalf to one of your friends), we collect the information about others that you give us in order to complete your request.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Of course, we also process your chats with other users as well as the content you publish, as part of the operation of the services.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Information we receive from others</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">In addition to the information you provide us directly, we receive information about you from others, including:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Other Users: Other users may provide information about you as they use our services. For instance, we may collect information about you from other users if they contact us about you.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Social Media: You may be able to use your social media login (such as Facebook Login) to create and log into your DoodlePad.In account. This saves you from having to remember yet another user name and password and allows you to share some information from your social media account with us.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Other Partners: We may receive info about you from our partners, for instance where DoodlePad.In ads are published on a partner&rsquo;s websites and platforms (in which case they may pass along details on a campaign&rsquo;s success).</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Information collected when you use our services</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">When you use our services, we collect information about which features you&rsquo;ve used, how you&rsquo;ve used them and the devices you use to access our services.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Usage Information: We collect information about your activity on our services, for instance how you use them (e.g- date and time you logged in, features you&rsquo;ve been using, searches, clicks and pages which have been shown to you, referring webpage address, advertising that you click on) and how you interact with other users (e.g- users you connect and interact with, time and date of your exchanges, number of messages you send and receive).</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Device information: We collect information from and about the device(s) you use to access our services, including: Hardware and software information such as IP address, device ID and type, device-specific and apps settings and characteristics, app crashes, advertising IDs (such as Google&rsquo;s AAID and Apple&rsquo;s IDFA, both of which are randomly generated numbers that you can reset by going into your device&rsquo; settings), browser type, version and language, operating system, time zones, identifiers associated with cookies or other technologies that may uniquely identify your device or browser (e.g., IMEI/UDID and MAC address) information on your wireless and mobile network connection, like your service provider and signal strength; information on device sensors such as accelerometers, gyroscopes and compasses.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Other information with your consent. If you give us permission, we can collect your precise geolocation (latitude and longitude) through various means, depending on the service and device you&rsquo;re using, including GPS, Bluetooth or Wi-Fi connections. The collection of your geolocation may occur in the background even when you aren&rsquo;t using the services if the permission you gave us expressly permits such collection. If you decline permission for us to collect your geolocation, we will not collect it.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Similarly, if you consent, we may collect your photos and videos (for instance, if you want to publish a photo, video or streaming on the services).</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">COOKIES AND OTHER SIMILAR DATA COLLECTION TECHNOLOGIES</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We use and may allow others to use cookies and similar technologies (e.g., web beacons, pixels) to recognize you and/or your device(s). You may read our Cookie Policy for more information on why we use them (such as authenticating you, remembering your preferences and settings, analyzing site traffic and trends, delivering and measuring the effectiveness of advertising campaigns, allowing you to use social features) and how you can better control their use, through your browser settings and other tools. Some web browsers (including Safari, Internet Explorer, Firefox and Chrome) have a &ldquo;Do Not Track&rdquo; (" DNT") feature that tells a website that a user does not want to have his or her online activity tracked. If a website that responds to a DNT signal receives a DNT signal, the browser can block that website from collecting certain information about the browser&rsquo;s user. Not all browsers offer a DNT option and DNT signals are not yet uniform. For this reason, many businesses, including DoodlePad.In, do not currently respond to DNT signals.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">HOW WE USE INFORMATION</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">The main reason we use your information is to deliver and improve our services. Additionally, we use your info to help keep you safe and to provide you with advertising that may be of interest to you. Read on for a more detailed explanation of the various reasons we use your information, together with practical examples.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To administer your account and provide our services to you</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Create and manage your account</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Provide you with customer support and respond to your requests</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Complete your transactions</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Communicate with you about our services, including order management and billing</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To help you connect with other users</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Analyze your profile and that of other users to recommend meaningful connections</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Show users&rsquo; profiles to one another</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To ensure a consistent experience across your devices</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Link the various devices you use so that you can enjoy a consistent experience of our services on all of them. We do this by linking devices and browser data, such as when you log into your account on different devices or by using partial or full IP address, browser version and similar data about your devices to help identify and link them.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To serve you relevant offers and ads</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Administer sweepstakes, contests, discounts or other offers</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Develop, display and track content and advertising tailored to your interests on our services and other sites</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Communicate with you by email, phone, social media or mobile device about products or services that we think may interest you</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To improve our services and develop new ones</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Administer focus groups and surveys</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Conduct research and analysis of users&rsquo; behavior to improve our services and content (for instance, we may decide to change the look and feel or even substantially modify a given feature based on users&rsquo; behavior)</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Develop new features and services (for example, we may decide to build a new interests-based feature further to requests received from users).</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To prevent, detect and fight fraud or other illegal or unauthorized activities</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Address ongoing or alleged misbehavior on and off-platform</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Perform data analysis to better understand and design countermeasures against these activities</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Retain data related to fraudulent activities to prevent against recurrences</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To ensure legal compliance</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Comply with legal requirements</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Assist law enforcement</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Enforce or exercise our rights, for example our Terms</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To process your information as described above, we rely on the following legal bases:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Provide our service to you: Most of the time, the reason we process your information is to perform the contract that you have with us. For instance, as you go about using our service to build meaningful connections, we use your information to maintain your account and your profile, to make it viewable to other users and recommend other users to you.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Legitimate interests: We may use your information where we have legitimate interests to do so. For instance, we analyze users&rsquo; behavior on our services to continuously improve our offerings, we suggest offers we think might interest you, and we process information for administrative, fraud detection and other legal purposes.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Consent: From time to time, we may ask for your consent to use your information for certain specific reasons. You may withdraw your consent at any time by contacting us at the address provided at the end of this Privacy Policy.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">HOW WE SHARE INFORMATION</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Since our goal is to help you make meaningful connections, the main sharing of users&rsquo; information is, of course, with other users. We also share some users&rsquo; information with service providers and partners who assist us in operating the services, with other group products and, in some cases, legal authorities. Read on for more details about how your information is shared with others.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">With other users: You share information with other users when you voluntarily disclose information on the service (including your public profile). Please be careful with your information and make sure that the content you share is stuff that you&rsquo;re comfortable being publicly viewable since neither you nor we can control what others do with your information once you share it.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">If you choose to limit the audience for all or part of your profile or for certain content or information about you, then it will be visible according to your settings.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">With our service providers and partners: We use third parties to help us operate and improve our services. These third parties assist us with various tasks, including data hosting and maintenance, analytics, customer care, marketing, advertising, payment processing and security operations.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We may also share information with partners who distribute and assist us in advertising our services. For instance, we may share limited information on you in hashed, non-human readable form to advertising partners.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We ensure to have strict confidentiality agreements when engaging any service provider or working with any partner. All of our service providers and partners must agree to strict confidentiality obligations.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">With other group products:. DoodlePad.In is part of the DoodlePad SofTech Private Limited and we have other products in the offering.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We may share your information with other group products to benefit you in two respects:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">for other group products to assist us in processing your information, as service providers, upon our instructions and on our behalf. Assistance provided by other group products may include technical processing operations, such as data hosting and maintenance, customer care, marketing and targeted advertising, finance and accounting assistance, better understanding how our service is used and users&rsquo; behavior to improve our service, securing our data and systems and fighting against spam, abuse, fraud, infringement and other wrongdoings.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">In order to improve your chances at building significant connections with others, we may make you visible on other group products or allow you to benefit from cross-platform functionalities. We will of course comply with applicable law and, where relevant, notify you of any such opportunity and allow you to agree or to refuse. Examples of such opportunities may include the creation of a new service within other group products, addressing a specific demographic that we feel would be interesting to you based on your search criteria.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We may also share information with other group products for legitimate business purposes such as corporate audit, analysis and consolidated reporting as well as compliance with applicable laws. We may also share user information with other group products to remove users who violate our terms of service, or have been reported for criminal activity and/or bad behavior. In some instances, we may remove that user from all platforms.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">For corporate transactions: We may transfer your information if we are involved, whether in whole or in part, in a merger, sale, acquisition, divestiture, restructuring, reorganization, dissolution, bankruptcy or other change of ownership or control.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">When required by law: We may disclose your information if reasonably necessary:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">(i) to comply with a legal process, such as a court order, subpoena or search warrant, government / law enforcement investigation or other legal requirements;</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">(ii) to assist in the prevention or detection of crime (subject in each case to applicable law); or</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">(iii) to protect the safety of any person.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">To enforce legal rights: We may also share information:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">(i) if disclosure would mitigate our liability in an actual or threatened lawsuit;</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">(ii) as necessary to protect our legal rights and legal rights of our users, business partners or other interested parties;</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">(iii) to enforce our agreements with you; and</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">(iv) to investigate, prevent, or take other action regarding illegal activity, suspected fraud or other wrongdoing.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">With your consent or at your request: We may ask for your consent to share your information with third parties. In any such case, we will make it clear why we want to share the information.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We may use and share non-personal information (meaning information that, by itself, does not identify who you are such as device information, general demographics, general behavioral data, geolocation in de-identified form), as well as personal information in hashed, non-human readable form, under any of the above circumstances. We may also share this information with other group products and third parties (notably advertisers) to develop and deliver targeted advertising on our services and on websites or applications of third parties, and to analyze and report on advertising you see. We may combine this information with additional non-personal information or personal information in hashed, non-human readable form collected from other sources. More information on our use of cookies and similar technologies can be found in our Cookie Policy.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">YOUR RIGHTS</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We want you to be in control of your information, so we have provided you with the following tools:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Access / Update tools in the service: Tools and account settings that help you to access, rectify or delete information that you provided to us and that&rsquo;s associated with your account directly within the service. If you have any question on those tools and settings, please contact our customer care for help.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Device permissions: Mobile platforms have permission systems for specific types of device data and notifications, such as phone book and location services as well as push notifications. You can change your settings on your device to either consent or oppose the collection of the corresponding information or the display of the corresponding notifications. Of course, if you do that, certain services may lose full functionality.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Deletion: You can deactivate your account by using the corresponding &lsquo;Deactivate&rsquo; functionality directly on the service or you can contact us to &lsquo;Suspend/Delete&rsquo; your account. However, &lsquo;Deactivating&rsquo; or &lsquo;Suspending&rsquo; or &lsquo;Deleting&rsquo; your account will only remove your profile from other user&rsquo;s view. Your information may however, show on certain search results. We also keep your information for record keeping.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We want you to be aware of your privacy rights. Here are a few key points to remember:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Updating your information: If you believe that the information we hold about you is inaccurate or that we are no longer entitled to use it and want to request its rectification, deletion or object to its processing, please contact our customer care.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">For your protection and the protection of all of our users, we may ask you to provide proof of identity before we can answer the above requests.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Keep in mind, we may reject requests for certain reasons, including if the request is unlawful or if it may infringe on trade secrets or intellectual property or the privacy of another user or if we need to keep your data for record keeping. If you wish to receive information relating to another user, such as a copy of any messages you received from him or her through our service, the other user will have to contact us to provide their written consent before the information is released. If you wish to receive information relating to another user, wherein a profile has been created without your consent, we may be able to pass on such information as per nature of the request.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Also, we may not be able to accommodate certain requests to object to the processing of personal information, notably where such requests would not allow us to provide our service to you anymore. For instance, we cannot provide our service if we do not have your date of birth.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Uninstall: You can stop all information collection by an app by uninstalling it using the standard uninstall process for your device. If you uninstall the app from your mobile device, the unique identifier associated with your device will continue to be stored. If you re-install the application on the same mobile device, we will be able to re-associate this identifier to your previous transactions and activities.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">HOW WE PROTECT YOUR INFORMATION</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We work hard to protect you from unauthorized access to or alteration, disclosure or destruction of your personal information. As with all technology companies, although we take steps to secure your information, we cannot guarantee, and you should not expect, that your personal information will always remain secure. We cannot be held liable if your information gets &lsquo;hacked&rsquo; and if it is leaked or gets public.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We regularly monitor our systems for possible vulnerabilities and attacks and regularly review our information collection, storage and processing practices to update our physical, technical and organizational security measures.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We may suspend your use of all or part of the services without notice if we suspect or detect any breach of security. If you believe that your account or information is no longer secure, please notify us immediately here</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">In order to ensure that our systems and your information are protected against unauthorized access, theft and loss, we implemented a bug bounty program. For more information about our bug bounty program, you can contact us</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">HOW LONG WE RETAIN YOUR INFORMATION</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">We keep your personal information only as long as we need it for legitimate business purposes and as permitted by applicable law. In practice, we do not delete or anonymize your information of your account because:</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">we must keep it to evidence our compliance with applicable law (for instance, records of consents to our Terms, Privacy Policy and other similar consents)</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">there is an outstanding issue, claim or dispute requiring us to keep the relevant information until it is resolved or</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">the information must be kept for our legitimate business interests, such as fraud prevention and enhancing users&rsquo; safety and security. For example, information may need to be kept to prevent a user who was banned for unsafe behavior or security incidents from opening a new account.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">CHILDREN&rsquo;S PRIVACY</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Our services are restricted to users who are 18 years of age or older. We do not permit users under the age of 18 on our platform and we do not knowingly collect personal information from anyone under the age of 18. If you suspect that a user is under the age of 18, please use the reporting mechanism available through the service.</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;">&nbsp;</p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">PRIVACY POLICY CHANGES</span></span></p>
<p class="western" lang="en-US" style="margin-bottom: 0cm; line-height: 100%;"><span style="font-family: Verdana, sans-serif;"><span style="font-size: small;">Because we're always looking for new and innovative ways to help you build meaningful connections, this policy may change over time. We may or may not notify changes to specific privacy policy changes</span></span></p>